end-2-end-cicd-pipeline-deployment

- This is a CICD pipeline that will allow me to automatically build, 
test and deploy my CloudFormation template to my TEST and PROD. environment. 
This project is one of many that i will be sharing as i continue to buld and 
strengthen my skills as an AWS DevOps Engineer. Please feel free to make inputs 
to the project, thanks and welcome.